apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: train-model-
spec:
  entrypoint: train-dag
  volumes:
  - name: model-storage
    persistentVolumeClaim:
      claimName: model-pvc

  templates:
  - name: train-dag
    dag:
      tasks:
      - name: train
        template: train-model
      - name: serve
        dependencies: [train]
        template: serve-model

  - name: train-model
    inputs:
      artifacts:
      - name: source
        path: /app
        git:
          repo: https://github.com/rohitjain994/mlops_automation.git
          revision: main
    container:
      image: python:3.9-slim
      command: ["sh", "-c"]
      args: ["pip install scikit-learn joblib && python /app/scripts/train.py"]
      volumeMounts:
      - name: model-storage
        mountPath: /mnt/data

  - name: serve-model
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: model-serving
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: model-serving
          template:
            metadata:
              labels:
                app: model-serving
            spec:
              containers:
              - name: server
                image: python:3.9-slim
                command: ["sh", "-c"]
                args: 
                - |
                  apt-get update && apt-get install -y git &&
                  git clone https://github.com/rohitjain994/mlops_automation.git /app &&
                  pip install fastapi uvicorn scikit-learn joblib &&
                  python /app/scripts/serve.py
                ports:
                - containerPort: 5000
                volumeMounts:
                - name: model-storage
                  mountPath: /mnt/data
              volumes:
              - name: model-storage
                persistentVolumeClaim:
                  claimName: model-pvc
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: model-service
        spec:
          type: NodePort
          selector:
            app: model-serving
          ports:
          - port: 5000
            targetPort: 5000
            nodePort: 30007
